import {useState} from "react";
import {evaluate,scenarios} from "./logic.mjs";
const explanations:Record<string,[string,string]>={
 identity_unconfirmed:["Participant identity is not established by a traceable participant-role candidate.","无法通过可回溯且角色为受试者的候选确认身份。"],
 call_evidence_missing:["No positive, finite system call duration is available in this toy scenario.","本合成场景没有有效的正数系统通话时长。"],
 positive_system_duration:["Positive system call duration provides this toy call-evidence route; no screenshot is required.","本演示中正数系统通话时长满足该电话证据路径，无需截图。"],
 chat_chain_incomplete:["Both enquiry and reply are needed for this toy chat chain.","本演示微信证据链需要同时有问询与回复。"],
 consent_not_covered:["Consent form is not covered; this does not automatically fail consistency.","知情表未覆盖；这一点不会自动判为不一致。"],
 unsupported_mode:["Unsupported modality requires review.","不支持的证据类型需复核。"]
};
export default function Demo({language}:{language:"en"|"zh"}){
 const zh=language==="zh";const [index,setIndex]=useState(0);const [duration,setDuration]=useState(0);const [ack,setAck]=useState(false);
 const item=scenarios[index];const result=evaluate({...item,duration:item.mode==="phone"?duration:item.duration});
 const select=(value:string)=>{const n=Number(value);setIndex(n);setDuration(scenarios[n].duration);setAck(false)};
 return <><h2>{zh?"合成证据 → 规则判断":"Synthetic evidence → rule decision"}</h2><p className="small">{zh?"预先构造的“提取字段”代替真实 OCR/LLM 输出。":"Fabricated extracted fields stand in for OCR/LLM output."}</p><div className="grid"><div className="panel"><div className="form"><label>{zh?"合成场景":"Synthetic scenario"}<select data-testid="scenario" value={index} onChange={e=>select(e.target.value)}>{scenarios.map((s,i)=><option key={s.id} value={i}>{s.id} · {s.label}</option>)}</select></label><div><h3>{zh?"虚构来源文字":"Fabricated source text"}</h3><pre>{item.text}</pre><p className="small">{zh?"预期身份标签":"Expected identity label"}: <code>{item.expected}</code></p></div><div className="table-scroll"><table><thead><tr><th>{zh?"候选标签":"Candidate"}</th><th>{zh?"角色":"Role"}</th><th>{zh?"可回溯":"Traceable"}</th></tr></thead><tbody>{item.candidates.map(c=><tr key={c.label}><td>{c.label}</td><td>{c.role}</td><td>{item.text.includes(c.label)?(zh?"是":"Yes"):(zh?"否":"No")}</td></tr>)}</tbody></table></div>{item.mode==="phone"&&<label>{zh?"合成系统通话时长（秒）":"Synthetic system call duration (seconds)"}<input data-testid="duration" type="number" min="0" max="3600" value={Number.isFinite(duration)?duration:""} onChange={e=>{setDuration(e.target.value===""?NaN:Number(e.target.value));setAck(false)}}/></label>}<p className="small">{zh?"证据类型":"Evidence route"}: {item.mode} · {zh?"知情表覆盖":"Consent coverage"}: {item.consentCovered?(zh?"覆盖":"Covered"):(zh?"未覆盖":"Not covered")}</p></div></div><div className="panel" aria-live="polite"><h3>{zh?"合成规则输出":"Synthetic rule output"}</h3><span data-testid="status" className={"badge "+(result.manualReview?"bad":"ok")}>{result.status==="consistent"?(zh?"一致（演示）":"Consistent · demo"):(zh?"不一致（演示）":"Inconsistent · demo")}</span><p>{result.manualReview?(zh?"人工复核：需要":"Manual review: required"):(zh?"人工复核：本示例未触发":"Manual review: not triggered by this example")}</p><ul>{[...result.reasons,...result.notes].map(key=><li key={key}>{explanations[key]?.[zh?1:0]||key}</li>)}</ul>{result.manualReview&&<div className="review"><button data-testid="review" className="primary" onClick={()=>setAck(true)}>{zh?"模拟确认已阅":"Acknowledge in demo"}</button></div>}{ack&&<p data-testid="ack" className="small">{zh?"仅在当前页面模拟已阅；原规则判断未改变，也没有创建真实审核记录。":"Acknowledged in this page only. The rule decision is unchanged; no real review record was created."}</p>}<div className="notice">{zh?"身份、证据形态、通话时长和未覆盖字段分别判断。提取候选本身不能授权最终结论。":"Identity, evidence route, call duration and uncovered fields are assessed separately. An extracted candidate alone does not authorize a final conclusion."}</div></div></div></>;
}
